=== vlad-avr/DS_Labs/Lab7/demo/target/classes/resources/xml/Schema.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified"
    xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="list">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="author" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="book" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:all minOccurs="1" maxOccurs="1">
                                        <xs:element type="xs:string" name="name" />
                                        <xs:element type="xs:double" name="price" />
                                        <xs:element name="genre">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:enumeration value="horror" />
                                                    <xs:enumeration value="scifi" />
                                                    <xs:enumeration value="adventure" />
                                                    <xs:enumeration value="comedy" />
                                                    <xs:enumeration value="drama" />
                                                    <xs:enumeration value="biography" />
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                    </xs:all>
                                    <xs:attribute type="xs:ID" name="id" use="required" />
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute type="xs:string" name="firstname" use="required" />
                        <xs:attribute type="xs:string" name="lastname" use="required" />
                        <xs:attribute type="xs:ID" name="id" use="required" />
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== vlad-avr/DS_Labs/Lab7/demo/target/classes/resources/xml/Data.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="Schema.xsd">
    <author firstname="Halo" lastname="John" id="A-1">
        <book id="B-1">
            <name>Covenant F*cker</name>
            <price>117</price>
            <genre>comedy</genre>
        </book>
        <book id="B-4">
            <name>Elite Elite</name>
            <price>5.5</price>
            <genre>scifi</genre>
        </book>
        <book id="B-5">
            <name>Grunty Flavour</name>
            <price>4.20</price>
            <genre>horror</genre>
        </book>
        <book id="B-8">
            <name>Reach: Glassification</name>
            <price>69.99</price>
            <genre>drama</genre>
        </book>
    </author>
    <author firstname="Lovecraft" lastname="Govard" id="A-2">
        <book id="B-2">
            <name>My Cat Niggerman</name>
            <price>14.88</price>
            <genre>horror</genre>
        </book>
        <book id="B-6">
            <name>At the Mountains of Shitpost</name>
            <price>16.16</price>
            <genre>comedy</genre>
        </book>
    </author>
    <author firstname="Matvienko" lastname="Volodymyr" id="A-3">
        <book id="B-3">
            <name>The Art of Being Old</name>
            <price>27.15</price>
            <genre>biography</genre>
        </book>
        <book id="B-9">
            <name>Laboratory Carnage</name>
            <price>23.23</price>
            <genre>horror</genre>
        </book>
    </author>
</list>
